import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  //const hello = api.post.hello.useQuery({ text: "from tRPC" });
  //console.log(hello.data);

  const allBlogs = api.post.getAllBlogs.useQuery();
  console.log(allBlogs.data);



  return (
    <>
      <Head>
        <title>Edit Text</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c] py-12 text-white">
        <div className="container  gap-12 px-4 mx-auto">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem] text-center">
             <span className="text-[hsl(280,100%,70%)]">Text</span> Edit
          </h1>

          <div className="mt-10 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {allBlogs.data?.map((blog)=>
            
            <Link href= {`/blog/${blog.id}`} key={blog.id}>
              <div className="rounded-xl bg-white/10 p-6">
                <h3 className="mb-4 text-2xl font-bold">{blog.title}</h3>
                <div className="mb4 text-lg">{blog.description}</div>
                <span className="text-base text-gray-400">{blog.createdAt.toLocaleDateString()}</span>
              </div>
            </Link>
            )}
            
          </div>
          <div className="mt-12 text-center">
            <Link href="/postBlog" className="rounded-md bg-orange-500 px-6 py-2 font-midium" >投稿する</Link>
          </div>
        </div>
      </main>
    </>
  );
}
