//インデックスページ
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import JSZip from "jszip";

export default function Home() {
  //const hello = api.post.hello.useQuery({ text: "from tRPC" });
  //console.log(hello.data);

  //全件取得
  const allTexts = api.post.getAllTexts.useQuery();
  console.log(allTexts.data);

  //テキストを投稿
  const postText = api.post.postTexts.useMutation({
  onSettled: () => {
    allTexts.refetch(); // これで一覧の再取得（リロード）をする
  },});

  //zipファイルのインポート
  const handleZipUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const zip = await JSZip.loadAsync(file);
      for (const fileName of Object.keys(zip.files)) {
        const zipEntry = zip.files[fileName]!;
        if (!zipEntry.name.endsWith(".txt")) continue;

        const content = await zipEntry.async("string");
      await postText.mutateAsync({
        title: zipEntry.name.replace(".txt", ""),
        description: content,
      });
    }

    alert("インポート完了");
  };



  return (
    <>
      <Head>
        <title>Edit Text</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" min-h-screen bg-gradient-to-b from-[#3a3a3a] to-[#000000] py-12 text-white">
        <div className="container  gap-12 px-4 mx-auto">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem] text-center">
             <span className="text-[hsl(280,100%,70%)]">Text</span> Edit
          </h1>

          <div className="mt-10 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {allTexts.data?.map((text)=>
            
            <Link href= {`/text/${text.id}`} key={text.id}>
              <div className="rounded-xl bg-white/10 p-6">
                <h3 className="mb-4 text-2xl font-bold">{text.title}</h3>
                <div className="mb4 text-lg">{text.description}</div>
                <span className="text-base text-gray-400">{text.createdAt.toLocaleDateString()}</span>
              </div>
            </Link>
            )}
            
          </div>
          <div className="mt-12 text-center">
            <Link href="/postText" className="rounded-md bg-orange-500 px-6 py-2 font-midium" >投稿する</Link>
          </div>
          <label
            htmlFor="zipUpload"
            className="inline-block cursor-pointer rounded bg-blue-600 px-6 py-3 font-semibold text-white hover:bg-blue-700 transition"
          >
          ZIPファイルを選択してインポート
          </label>
          <input
            type="file"
            accept=".zip"
            id="zipUpload"
            onChange={handleZipUpload}
            className="hidden"
          />

        </div>
      </main>
    </>
  );
}
